Avoid removing alt playlists
Signed-off-by: Christopher Larson <kergoth@gmail.com>

diff --git a/hooks/alternatives_after_update b/hooks/alternatives_after_update
--- a/hooks/alternatives_after_update
+++ b/hooks/alternatives_after_update
@@ -14,8 +14,31 @@ scriptdir="$(cd "$(dirname "$0")" && pwd -P)"
 alternative="$1"
 directory="$2"
 
+if ! [ -d "$directory" ]; then
+    echo >&2 "Error: $directory does not exist after alternative update"
+    exit 1
+fi
+
 if [ -n "${BEETS_SKIP_HOOKS:-}" ]; then
     exit 0
+fi
+
+if [ -z "${BEETS_LIBRARY:-}" ]; then
+    msg "Warning: BEETS_LIBRARY not set, skipping playlist clean up."
+elif [ -d "${BEETS_LIBRARY:-}" ]; then
+    msg "Removing remnant playlists"
+    playlistdir="$(config_value 'alternativesplaylist.playlist_dir' || config_value 'playlist.playlist_dir' Playlists)"
+    playlistdir="$(basename "$playlistdir")"
+    if [ -n "$playlistdir" ] && [ -d "$directory/$playlistdir" ]; then
+        find "$directory/$playlistdir" -type f \
+            | while read -r fn; do
+                rel="${fn#$directory/}"
+                if ! [ -e "$BEETS_LIBRARY/$rel" ]; then
+                    msg "$BEETS_LIBRARY/$rel does not exist, but $fn does, removing"
+                    rm -fv "$fn"
+                fi
+            done
+    fi
 fi
 
 if [ -z "${BEETS_ALT_SKIP_COVERS:-}" ]; then
@@ -31,5 +54,5 @@ if [ -d "$directory/.git" ]; then
         cd "$directory" || exit 1
         git add -A .
         git commit -m "Update"
-    )
+    ) || :
 fi
